RegService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/', include('registration.urls', namespace='register')),
    path('', include('registration.urls', namespace='home')),
    path('accounts/', include('allauth.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path, include
from .views import(

    RegistrationView,
    DriverInfoView,
    DriverInfoUpdate,
    load_cities,
    activate,
    DriverListView,
)

from .functions import render_pdf_view, export_excel

app_name = 'registration'


urlpatterns = [
    path('registration', RegistrationView.as_view(), name='registration'),
    path('', RegistrationView.as_view(), name='registration'),
    path('info_view', DriverInfoView.as_view(), name='info_view'),
    path('info_update/<pk>', DriverInfoUpdate.as_view(), name='info_update'),
    path('ajax/load_cities/', load_cities, name='load_cities'),
    path('activate/<token>', activate, name='activate'),
    path('list_view', DriverListView.as_view(), name='list_view'),
    path('list_view_pdf', render_pdf_view, name='list_view_pdf'),
    path('export_excel', export_excel, name='export_excel'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl" >
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}

    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %} >
    <link rel="stylesheet" href={% static 'css/mdb.min.css' %} >
    <link rel="stylesheet" href={% static "css/style.min.css" %} >
    <link rel="stylesheet" href={% static "css/style2.css" %} >


    <style>
*{
    padding: 0;
    margin: 0;
    font-family:Shabnam, 'Segoe UI',sans-serif;
    {#text-decoration: none;#}
    direction: rtl;
    {#color: black;#}
    box-sizing: border-box;
    {#font-weight: 500;#}
}
</style>




{% include 'navbar.html' %}
</head>
<body>
{#    {% if form.non_field_errors %}#}
{#        <div class="card alert alert-dismissible alert-danger shadow text-right mb-3 ">#}
{#        {{ form.non_field_errors }}#}
{#        <button type="button" class="close " data-dismiss="alert" aria-label="Close">#}
{#            <span aria-hidden="true" class="red-text" >&times;</span>#}
{#        </button>#}
{#        </div>#}
{#  {% endif %}#}
{#    {% for field in form %}#}
{#        {% if field.errors %}#}
{#            <div class="card alert btn-danger alert-dismissible shadow text-right mt-0 mb-3 container">#}
{#              {% for error in field.errors %}#}
{#               <span>{{ error }}</span>#}
{#                   <button  type="button" class="close  flex-center"   data-dismiss="alert" aria-label="Close" >#}
{#                   <span aria-hidden="true" class="red-text" >&times;</span>#}
{#                   </button>#}
{#              {% endfor %}#}
{#            </div>#}
{##}
{#        {% endif %}#}
{#    {% endfor %}#}

{% if messages  %}
    {% for message in messages %}
<div  class="card-header shadow alert btn-danger alert-dismissible fade show text-right container " >
   {{ message|safe }}
  <button  type="button" class="close flex-center"  data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true" >&times;</span>
  </button>
</div>
    {% endfor %}
{% endif %}

{#<div style="margin-top: 50px">#}
{% block content%}

{% endblock %}
{#</div>#}
{% load static %}



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

</body>

templates/code_confirm.html
{% extends 'base.html' %}

{% block content %}

    <style>


        #head {
            margin: auto;
            text-align: center;
            background-color: floralwhite;
            text-shadow:2px 2px 5px darkgrey;
            padding: 75px 50px;
            max-width: 30vw;
            min-width: 400px;
            border-radius: 8px;
            box-sizing: border-box;
            font-family: "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";

        }

        #card-form {
            max-width: 30vw;
            min-width: 400px;
            margin: auto;
            padding: 20px 10px;
            border-radius: 8px;
            text-align: right;
        }

        .card {
            display: block;
            direction: rtl;
            padding: 20px 50px;
            margin: auto;
            max-width: 400px;
            min-width: 70%;
        }

        #input {
            margin: 5% 0;
            width: 70%;
            font-family: "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";


        }
        #2{
            display: none;
        }

        #but1, #but2 {
            margin: auto;
            padding: 13px 55px;
            font-family: "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
            box-sizing: border-box;
        }



    </style>



    <div id="head" class="card-header shadow">
        <h1>سامانه ثبت نام رانندگان</h1>
        <h2>(تایید)</h2>
    </div>
    <div id="card-form" class="card shadow">

        <form method="POST" action={% url 'registration:activate' token   %}>
            {% csrf_token %}
            <div id="2" hidden>
                {{ from.as_table }}
                </div>

            <div class="card ">



                    <input id="input" class="form-control pt-2 pb-2" type="number" placeholder="کد ارسال شده را وارد نمایید" name="email_token">

                </span>
               <span>
                     <button type="submit" id="but1" class="btn btn-red rounded">تایید</button>
               </span>
            </div>
        </form>
    </div>

{% endblock %}

templates/driver_info_view.html
{% extends 'base.html' %}

{% block content %}

<style>



#head {
    margin:auto;
    text-align:center ;
    background-color: floralwhite;
    text-shadow:2px 2px 5px darkgrey;
    padding:75px 50px ;
    max-width: 30vw;
    min-width: 500px;
    border-radius: 8px;
    font-family:  "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";

}

#card-form {
    max-width: 30vw;
    margin: auto;
    padding: 40px 50px 25px;
    border-radius: 8px;
    align-content: start;
    text-align: right;
    min-width: 500px;
}
#input{
    margin:5% auto;
    align-items: center;
}

#but1,#but2,#but3 {

    padding: 13px 55px;
    font-family: "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    box-sizing: border-box;
}



.form-row div, .form-group div{
    padding: 28px 20px;
    direction: rtl;
}

#table {

    margin:0 auto 1vw;
    width: 80%;
    height: 300px;
    border-collapse: collapse;
    overflow-x:auto;
    box-shadow:1px 1px 15px lightgray;
    font-family:"Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}

#table td, #table th {
    {#border: 1px solid #ddd;#}
    padding: 8px;
    margin:0

}


#table th{
    font-size:  16px   ;
    background-color: darkcyan;
    text-align: center;

}

#table td{
    width: 1%;
    line-height: 35px;
}



#table  tr:nth-child(even){
    background-color: floralwhite;

}

#table tr:hover{
    background-color: darkgrey;
}


</style>



    <div id="head" class="card-header shadow"  >
        <h1  >سامانه ثبت نام رانندگان</h1>
            <h2>(نمایش و ویرایش)</h2>
    </div>
    <div id="card-form" class="card shadow" >
        <form  method="post" action={% url 'registration:info_view' %} >
            {% csrf_token %}

            <input class="form-control col-6 mr-2 d-sm-inline-block" style="direction: rtl;" type="number" placeholder="کد ملی" name="national_id">
            <div id="input">
            <input id="but1" class="btn btn-red rounded "  type="submit" value="جستجو">
            <a  id="but2" class="btn btn-primary rounded" href={% url 'registration:registration' %} >بازگشت</a>

            </div>
        </form>
        {% if table_display %}
        <div class="datatable" data-pagination="false" data-striped="true" data-borderless="true" data-loader-class="bg-success" data-max-height="320px" data-color="light-blue" data-border-color="success">
            <table id="table" >
				<tr>
                    <td class="font-weight-bold col-3" >کد ملی</td>
                    <td>{{ driver.national_id }}</td>

                </tr>

                <tr>
                    <td class="font-weight-bold  ">کارت هوشمند</td>
                    <td>{{ driver.smart_card_number }}</td>

                </tr>

                <tr>
                    <td class="font-weight-bold  ">تلفن همراه</td>
                   <td>{{ driver.cellnumber }}</td>

                </tr>

                <tr>
                    <td class="font-weight-bold">ایمیل</td>
                     <td>{{ driver.email }}</td>

                </tr>


                <tr>
                    <td class="font-weight-bold">نام</td>
                    <td>{{ driver.name }}</td>

                </tr>

                <tr>
                    <td class="font-weight-bold">نام خانوادگی</td>
                    <td>{{ driver.family }}</td>

                </tr>

                <tr>
                    <td class="font-weight-bold">استان</td>
                    <td>{{ driver.state }}</td>

                </tr>

                <tr>
                    <td class="font-weight-bold">شهر</td>
                    <td>{{ driver.city }}</td>

                </tr>

                <tr>

                   <td colspan="2"> <a id="but3" class="btn btn-red rounded " href={{driver.get_driver_info_update_url}}>ویرایش</a></td>
                </tr>

			</table>

        </div>
        {% endif %}


    </div>


{% endblock %}

templates/driver_list_view.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">



#head {
    margin:auto;
    text-align:center ;
    background-color: floralwhite;
    text-shadow:2px 2px 5px darkgrey;
    padding:75px 50px ;
    max-width: 30vw;
    min-width: 500px;
    border-radius: 8px;

}

#card-form {
    max-width: 30vw;
    margin: auto;
    padding: 40px 50px 10px;
    border-radius: 8px;
    align-content: start;
    text-align: right;
    min-width: 500px;
}
#input{
    margin:5% auto;
    align-items: center;
}

#but1,#but2 {
    margin-top: 0;
    padding: 10px 30px;
    box-sizing: border-box;
}
#but1 {

    padding: 10px 35px;

}



#table {
    direction: rtl;
    margin:0 auto 20px;
    width: 80%;
    min-height:600px;
    row-gap: 10px;
    border-collapse: collapse;
    overflow-x:auto;
    box-shadow:1px 1px 15px lightgray;
}

#table td{
    border-bottom:1px solid #ddd;
    text-align: center;
    padding: 8px;
    margin:0;


}


#table th{
    height: 61px;
    font-size:  15px   ;
    border-bottom:1px solid #ddd;
    text-align: center;
    padding: 8px;
    background-color: whitesmoke;

}


#table  tr:nth-child(even){
    background-color: floralwhite;

}

#table tr:hover{
    background-color: darkgrey;
}

#td1{
    background-color: whitesmoke;
}

</style>



    <div id="head" class="card-header shadow"  >
        <h1  >سامانه ثبت نام رانندگان</h1>
            <h2>(لیست رانندگان)</h2>
    </div>
    <div id="card-form" class="card shadow" >




        <div >
            <table id="table" >
				<tr >
                    <th class="font-weight-bold"  >ردیف</th>
                    <th  >کد ملی</th>
                    <th >کارت هوشمند</th>
                    <th >نام</th>
                    <th>نام خانوادگی</th>
                </tr>
                {% for driver in drivers %}
                <tr>
                    <td id="td1">{{ forloop.counter}}</td>
                    <td>{{ driver.national_id }}</td>
                    <td>{{ driver.smart_card_number }}</td>
                    <td>{{ driver.name }}</td>
                    <td>{{ driver.family }}</td>
                </tr>
                {% endfor %}
			</table>
   {% if is_paginated %}
            <nav class="d-flex justify-content-center wow fadeIn ">
                <ul class="pagination primary mb-0">

                    <!--Arrow left-->
                    {% if page_obj.has_previous %}
                    <li class="page-item ">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo; </span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <a class="page-link">
                            <span >{{ page_obj.number }}</span>
                        </a>
                    </li>

                    {% if page_obj.has_next %}
                    <li class="page-item ">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

            <div id="input">
            <a  id="but2" class="btn btn-dark-green rounded" href={% url 'registration:export_excel' %} >Excel دانلود</a>
            <a  id="but1" class="btn btn-danger rounded" href={% url 'registration:list_view_pdf' %} > PDF دانلود </a>


            </div>
        </div>



    </div>


{% endblock %}

templates/driverinfo_update_form.html
{% extends 'base.html' %}


{% block content %}

    <style>
        #table{
            margin: auto;
            max-width: 600px;
        }

        #table td {
            width: 10%;
            line-height: 50px;
            {#border-bottom:1px   grey  solid;#}

            padding: 0 5px

        }

        #table tr:nth-child(even) {
            background-color: floralwhite;

        }




        .form-row div, .form-group div {
            direction: rtl;
        }


        #card-form {

            margin: auto;
            padding: 20px 15px;
            border-radius: 8px;
            text-align: right;
            {#width: 65vw;#}
            box-sizing: border-box;
        }

        #head {
            margin: auto;
            text-align: center;
            background-color: floralwhite;
            width: 80vw;
            border-radius: 8px;
            font-family: "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        }


        #but1, #but2 {
            box-sizing: border-box;
            padding: 13px 55px;
        }

    </style>
    {% if form.non_field_errors %}
        <div class="card alert alert-dismissible alert-danger shadow text-right mb-3 ">
        {{ form.non_field_errors }}
        <button type="button" class="close " data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" class="red-text" >&times;</span>
        </button>
        </div>
  {% endif %}
    {% for field in form %}
        {% if field.errors %}
            <div class="card alert btn-danger alert-dismissible shadow text-right mt-0 mb-3 container">
              {% for error in field.errors %}
               <span>{{ error }}</span>
                   <button  type="button" class="close  flex-center"   data-dismiss="alert" aria-label="Close" >
                   <span aria-hidden="true" class="red-text" >&times;</span>
                   </button>
              {% endfor %}
            </div>

        {% endif %}
    {% endfor %}

    <div id="head" class="card-header shadow"  >
        <h1  >سامانه ثبت نام رانندگان</h1>
            <h2>(ویرایش)</h2>
    </div>
    <div id="card-form" class="card shadow">
        <div class="datatable" data-pagination="false" data-striped="true" data-borderless="true"
             data-loader-class="bg-success" data-max-height="320px" data-color="light-blue" data-border-color="success">
            <form action="" method="post">
                {% csrf_token %}
                <table class=" shadow  " id="table">
                    <tr>
                        <td class=" font-weight-bold  ">کارت هوشمند</td>
                        <td>{{ form.smart_card_number }}</td>

                    </tr>

                    <tr>
                        <td class="font-weight-bold  ">تلفن همراه</td>
                        <td>{{ form.cellnumber }}</td>


                    </tr>

                    <tr >
                        <td class="font-weight-bold ">ایمیل</td>
                        <td>{{ form.email }}</td>

                    </tr>

                    <tr>
                        <td class="font-weight-bold">نام</td>
                        <td>{{ form.name }}</td>

                    </tr>

                    <tr>
                        <td class="font-weight-bold">نام خانوادگی</td>
                        <td>{{ form.family }}</td>

                    </tr>

                    <tr>
                        <td class="font-weight-bold">استان</td>
                        <td>{{ form.state }}</td>

                    </tr>

                    <tr>
                        <td class="font-weight-bold">شهر</td>
                        <td>{{ form.city }}</td>

                    </tr>


                </table>

                <div id="input">
                          <input id="but1" class="btn btn-red rounded " type="submit" name="submit"
                           value="ویرایش">

                    <a id="but2" class="btn btn-primary rounded" href={% url 'registration:info_view' %}> بازگشت </a>


                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/list_pdf.html
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <style>

body{
    margin-top: 8%;
    font-family: Shabnam, sans-serif;
}
@font-face {
    font-family:Shabnam;
    src: url('C:\myfolder\Shabnam.ttf');
}

#table {
    direction: rtl;
    margin: 0 auto 20px;
    width: 80%;
    min-height: 600px;
    row-gap: 10px;
    border-collapse: collapse;
    overflow-x: auto;
    box-shadow: 1px 1px 15px lightgray;
    {#font-family: Shabnam, "Segoe UI", sans-serif;#}
}

#table td{
    border-bottom:1px solid #ddd;
    text-align: center;
    padding: 8px;
    margin:0;


}
#img {
    display: inline-block;
    margin-left: 33vw;
    border: 2px solid black;
    box-sizing: border-box;
    height: 250px;

}

#table th{
    height: 61px;
    font-size:  15px   ;
    border-bottom:1px solid #ddd;
    text-align: center;
    padding: 8px;
    background-color: whitesmoke;

}


#table  tr:nth-child(even){
    background-color: floralwhite;

}

#table tr:hover{
    background-color: darkgrey;
}

#td1{
    background-color: whitesmoke;
}

    </style>
</head>

<body>


<div id="card-form" class="card shadow" >


        <div >
        <pdf:language name="persian"/>
            <table id="table" >
				<tr >
                    <th>نام خانوادگی</th>
                    <th >نام</th>
                    <th >کارت هوشمند</th>
                    <th  >کد ملی</th>
                    <th id="td1" class="font-weight-bold"  >ردیف</th>
                </tr>
                {% for driver in drivers %}
                <tr>

                    <td>{{ driver.family }}</td>
                    <td>{{ driver.name }}</td>
                    <td>{{ driver.smart_card_number }}</td>
                    <td>{{ driver.national_id }}</td>
                    <td >{{ forloop.counter}}</td>

                </tr>

                {% endfor %}
			</table>
        </div>
 </div>
</body>
</html>

templates/loaded_cities.html
<option value="">انتخاب شهر</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/navbar.html
{% load static %}

{#navbar bootstarp#}

{#<div class="jumbotron tempting-azure-gradient " style="margin-bottom: 0;padding:25px; text-align: right">#}
{#    <h2>شرکت خدمات بیمه ای پیام رسانان آتیه روشن </h2>#}
{#</div>#}

{#<div >#}
<nav class="navbar navbar-expand-md navbar-light bg-white shadow sticky-top mb-4">
    <div>
 <img class="img-fluid  mr-md-5 ml-md-5 mr-sm-2"  src={% static 'img/II2.png' %} alt="" height="95" width="95">
    </div>
    <button class="navbar-toggler white border  " data-toggle="collapse" data-target="#collapse_target">
        <span class="navbar-toggler-icon "></span>
    </button>

{#    bootstrap collpase#}
    <div class="collapse  navbar-collapse text-right "  id="collapse_target">



    <ul class="navbar-nav mb-0 mt-5">

        <li class="nav-item">
            <a class="nav-link ml-3" href={% url "registration:registration" %}>
                <img src={% static 'img/icons/signup.png' %} alt="">
                ثبت نام

            </a>
        </li>
        <div class="dropdown-divider black"></div>
        <li class="nav-item">
            <a class="nav-link ml-3" href={% url "registration:info_view" %}>
              <img src={% static 'img/icons/search.png' %} alt="">
                جستجوی کد ملی
            </a>
        </li>
         <div class="dropdown-divider black"></div>
        <li class="nav-item">
            <a class="nav-link ml-3" href={% url "registration:registration" %}>
                <img src={% static 'img/icons/contact_us.png' %} alt="">
                تماس با ما
            </a>
        </li>
        <div class="dropdown-divider "></div>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link ml-3" href={% url 'registration:list_view' %}>
                    <img src={% static 'img/icons/list.png' %} alt="">
                    لیست اسامی
                </a>
            </li>
            <div class="dropdown-divider black"></div>
            <li class="nav-item">
                <a class="nav-link ml-3" href={% url 'account_logout' %}>
                    <img  src={% static 'img/icons/logout2.png' %}  >
                    خروج
                </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link ml-3" href={% url 'account_login' %}>
                    <img src={% static 'img/icons/login2.png' %}>
                    ورود
                </a>
            </li>
        {% endif %}
    </ul>
        </div>
</nav>

{#</div>#}

templates/registration.html
{% extends 'base.html' %}


{% block content %}

    <style>




#head {
    margin: auto;
    text-align: center;
    background-color: floralwhite;
    padding: 75px 50px;
    max-width: 30vw;
    min-width: 400px;
    text-shadow:2px 2px 5px darkgrey;
    border-radius: 8px;
    box-sizing: border-box;


}

#card-form {

    max-width: 30vw;
    min-width: 400px;
    max-height: max-content;
    margin: auto;
    padding: 20px 10px;
    border-radius: 8px;
    text-align: right;
}

.card {
    display: block;
    direction: rtl;
    max-height: max-content;
    padding: 20px 50px;
    margin: auto;
    max-width: 400px;
    min-width: 70%;
}

#but1 {

    padding: 13px 55px;

}


</style>



    <div id="head" class="card-header shadow">
        <h1>سامانه ثبت نام رانندگان</h1>
    </div>
    <div id="card-form" class="card shadow">
        <div class="card form-group ">
        <form action="" method="post" id="personForm"  data-cities-url= {% url 'registration:load_cities' %} >
            {% csrf_token %}

                <span class="form col-md-6 mb-3 mt-0">

                    {{ form.national_id }}
                    <span class="red-text mb-0 pb-0">{{ form.national_id.errors }}</span>

                </span>

                <span class="form col-md-6 mb-3  ">

                {{ form.smart_card_number }}
                <span class="red-text mb-0 pb-0">{{ form.smart_card_number.errors }}</span>

                </span>

                <span class="form col-md-6 mb-3">

                    {{ form.name }}
                    <span class="red-text mb-0 pb-0">{{ form.name.errors }}</span>

                </span>

                <span class="form col-md-6 mb-3">

                    {{ form.family }}
                    <span class="red-text mb-0 pb-0">{{ form.family.errors }}</span>

                </span>

                <span class="form col-md-6 mb-3">

                {{ form.cellnumber }}
                <span class="red-text mb-0 pb-0">{{ form.cellnumber.errors }}</span>

                </span>

                <span  class="form col-md-6 mb-3 ">

                    {{ form.email }}
                    <span class="red-text mb-0 pb-0">{{ form.email.errors }}</span>

                </span>


                <span class="form col-md-6 mb-3">

                    {{ form.state }}
                    <span class="red-text mb-0 pb-0">{{ form.state.errors }}</span>

                </span>

                <span  class="form col-md-6  ">

                    {{ form.city }}
                    <span class="red-text mb-0 pb-0">{{ form.city.errors }}</span>

                </span>


                <div id="input">
                    <input id="but1" class="btn btn-primary rounded " type="submit" name="submit"
                           value="ثبت نام">

                </div>

        </form>


    </div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <script>
            $('#id_state').change(function () {
                var url = $('#personForm').attr('data-cities-url');
                var state_id = $(this).val(); //or $('#id_state').val() this.value// gets the selected state ID from html input

                $.ajax({    //initialize an AJAX request
                    url: url, //set the url of the request
                    data: {
                        'state': state_id  //add the state  to request values
                    },
                    success: function (data,ResponseText,status,xhr) { // data is returned as result of load cities function
                        {#console.log(data)#}
                        {#console.log(ResponseText)#}
                        {#console.log(status)#}
                        {#console.log(xhr)#}
                        $("#id_city").html(data) //load the data that came form server into html
                    }
                });


            });

        </script>
    </div>


{% endblock %}